### ISSUE TITLE
一些反馈：config相关，help相关，-t相关

### ISSUE THREAD

**Issue by Oaklight** [Karmenzind/kd#53]
```toml
paging = true
pager_command = "less -RF"
auto_clear = true
english_only = false
theme = "temp"
http_proxy = ""
clear_screen = false
freq_alert = true

[logging]
  enable = true
  path = ""
  level = "info"
  stderr = false
  redirect_to_stream = false
```
设置后并没有清除terminal，同时kd --generate-config允许覆盖之后，config内容无变化

-t模式卡死

-h缺少新的一些指令说明
